api = "0.2"

[buildpack]
id = "petermylemans/elastic-apm-cnb"
homepage = "https://github.com/petermylemans/elastic-apm-cnb"
name = "Elastic APM Buildpack"

[metadata]
include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
pre-package = "./scripts/build.sh"

[[metadata.dependencies]]
id = "elastic-apm-agent-java"
name = "Elastic APM Java Agent"
version = "1.26.0"
uri = "https://repo1.maven.org/maven2/co/elastic/apm/elastic-apm-agent/1.26.0/elastic-apm-agent-1.26.0.jar"
sha256 = "ede259f672f6dd4e6ec95b5ae6031df4dcde1b5e269509faca532e48ad168d14"
stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]

[[metadata.dependencies.licenses]]
type = "Apache License 2.0"
uri = "https://github.com/elastic/apm-agent-java/blob/master/LICENSE"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
