api = "0.2"

[buildpack]
id = "petermylemans/elastic-apm-cnb"
homepage = "https://github.com/petermylemans/elastic-apm-cnb"
name = "Elastic APM Buildpack"

[metadata]
include-files = ["bin/run", "bin/build", "bin/detect", "buildpack.toml"]
pre-package = "./scripts/build.sh"

[[metadata.dependencies]]
id = "elastic-apm-agent-java"
name = "Elastic APM Java Agent"
version = "1.23.0"
uri = "https://repo1.maven.org/maven2/co/elastic/apm/elastic-apm-agent/1.23.0/elastic-apm-agent-1.23.0.jar"
sha256 = "c7be5e9c35c4e80ec1fbcf8f559f0f5724d56c4b89cd72d7c7497198d764e119"
stacks = ["io.buildpacks.stacks.bionic", "org.cloudfoundry.stacks.cflinuxfs3"]

[[metadata.dependencies.licenses]]
type = "Apache License 2.0"
uri = "https://github.com/elastic/apm-agent-java/blob/master/LICENSE"

[[stacks]]
id = "io.buildpacks.stacks.bionic"

[[stacks]]
id = "org.cloudfoundry.stacks.cflinuxfs3"
